Added missing non-printing byte order mark in Japanese.
This fixes a syntax error when checking with 'msgfmt -c'.

When you startup the Zope instance with Japanese enabled (in
PTS_LANGUAGES and zope_i18n_allowed_languages) you would get a
PoSyntaxError from python-gettext, which in turn would raise a
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position
0: ordinal not in range(128)