add two new messages in plone-manual.pot that i18ndude can't extract because of a zope.tal error
OpenTagError: Tag <ul> is not allowed in <nav>, at line 14, column 7 in plone.app.event/plone/app/event/browser/event_listing.pt